plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace 'com.example.demofusedlib'
    compileSdk {
        version = release(36)/*  {
            minorApiLevel = 1
        } */
    }

    defaultConfig {
        applicationId "com.example.demofusedlib"
        minSdk 25
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        compose true
        viewBinding true
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.lifecycle.runtime.ktx

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)

    implementation libs.androidx.activity.compose
    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.compose.ui
    implementation libs.androidx.compose.ui.graphics
    implementation libs.androidx.compose.ui.tooling.preview
    implementation libs.androidx.compose.material3
    implementation libs.androidx.constraintlayout

    // test method 1
    // depend on modules directly
    // implementation(project(":aarhelloworld1"))
    // implementation(project(":aarhelloworld2"))
    // implementation(project(":aarhelloworld3"))
    // implementation(project(":apilocalaar"))
    // implementation(project(":libhelloworld1"))
    // implementation(project(":libhelloworld2"))

    // test method 2
    // depend on local aar under libs dirs
    // implementation fileTree(include: ["*.jar", "*.aar"], dir: "libs")
    // implementation files("libs/aarhelloworld1-debug.aar")
    // implementation files("libs/aarhelloworld2-debug.aar")
    // implementation files("libs/aarhelloworld3-debug.aar")
    // implementation files("libs/apilocalaar-debug.aar")
    // implementation files("libs/libhelloworld1-debug.aar")
    // implementation files("libs/libhelloworld2-debug.aar")

    // test method 3 my-fused-library-1.0.aar
    // depend on my-fused-library-1.0.aar which includes all aars.
    implementation files("libs/my-fused-library-1.0.aar")

    // test method 4 my-fused-library-1.0.aar
    // depend on modules, aars in local repository, under libs dirs
    // implementation(project(":localrepo:helloworld1"))
    // implementation(project(":localrepo:helloworld2"))
    // implementation(project(":localrepo:helloworld3"))
    // implementation(project(":apilocalaar"))
    // implementation(project(":libhelloworld1"))
    // implementation(project(":libhelloworld2"))


    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core

    androidTestImplementation platform(libs.androidx.compose.bom)
    androidTestImplementation libs.androidx.compose.ui.test.junit4
    debugImplementation libs.androidx.compose.ui.tooling
    debugImplementation libs.androidx.compose.ui.test.manifest
}