pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "DemoFusedLib"
include ':app'
include ':fusedlib'
include ':localrepo:helloworld1'
include ':localrepo:helloworld2'
include ':localrepo:helloworld3'
include ':apilocalaar'

include ':aarhelloworld1'
include ':aarhelloworld2'
include ':aarhelloworld3'
include ':libhelloworld1'
include ':libhelloworld2'

